### ISSUE TITLE
[FEATURE] Add a landing page 

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/open-API#3]
### Description

Add a landing page for the root

**Comment by Pradumnasaraf** [comment]
> Hi, do you have an idea of what you want the landing page to look like? Do you want to use react or vanillaJS?

Hey! I am thinking of a basic website with HTML and CSS website because mainly it will reset CRUD operations!!

**Comment by Adithya-Sr** [comment]
Can i work on this one? If yes, is this the page you want to modify?
![Web capture_22-8-2022_03219_localhost](https://user-images.githubusercontent.com/97578285/185806904-7838860f-d05e-487c-b7df-0eec2e51bf79.jpeg)

**Comment by Pradumnasaraf** [comment]
> Can i work on this one? If yes, is this the page you want to modify?
> ![Web capture_22-8-2022_03219_localhost](https://user-images.githubusercontent.com/97578285/185806904-7838860f-d05e-487c-b7df-0eec2e51bf79.jpeg)
> 

Hey the issue is already fixed thanks. Sorry for not closing it.

**Comment by Adithya-Sr** [comment]
> Hey the issue is already fixed thanks. Sorry for not closing it.

 No problem 👍
